# Generated by Django 5.1.2 on 2024-10-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/ds8x1i3zm/image/upload/default_post_b29qkk.jpg', upload_to='images/'),
        ),
    ]
