# Generated by Django 3.2.25 on 2024-10-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/ds8x1i3zm/image/upload/default_profile_mcrw02.jpg', upload_to='images/'),
        ),
    ]
